

[communications.sms]
http_base = "https://sms-api.internal:3000" # REQUIRED
certificate_path = "sms-api.internal.ca.crt"
auth = "test"
recipients = [ # REQUIRED
    { target = "+4412345678", level = 3 }, # Receive all alert levels
    { target = "+4487654321", level = 4 }, # Receive only Alarm alerts
]


[communications.pushover]
token = "abc123"
recipients = [ # OPTIONAL
    { target = "abc123_user_token", level = 3 }
]
